//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_COLONIA
    {
        public C_COLONIA()
        {
            this.C_PERSONA = new HashSet<C_PERSONA>();
        }
    
        public int ID_COLONIA { get; set; }
        public string DSC_COLONIA { get; set; }
        public int ID_DELEG_MUNICIPIO { get; set; }
        public int ID_ESTADO { get; set; }
        public string NUM_CP { get; set; }
        public Nullable<int> ZZ_MIGRA_IP104040 { get; set; }
    
        public virtual C_DELEG_MUNICIPIO C_DELEG_MUNICIPIO { get; set; }
        public virtual ICollection<C_PERSONA> C_PERSONA { get; set; }
    }
}
