//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DELEG_MUNICIPIO
    {
        public C_DELEG_MUNICIPIO()
        {
            this.C_COLONIA = new HashSet<C_COLONIA>();
        }
    
        public int ID_DELEG_MUNICIPIO { get; set; }
        public string DSC_DELEG_MUNICIPIO { get; set; }
        public int ID_ESTADO { get; set; }
        public Nullable<int> ID_C4 { get; set; }
        public Nullable<int> ZZ_MIGRA_IP104040 { get; set; }
    
        public virtual ICollection<C_COLONIA> C_COLONIA { get; set; }
    }
}
