//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ESTADO_CIVIL
    {
        public C_ESTADO_CIVIL()
        {
            this.C_PERSONA = new HashSet<C_PERSONA>();
        }
    
        public int ID_ESTADO_CIVIL { get; set; }
        public string DSC_ESTADO_CIVIL { get; set; }
        public int ID_ESTATUS { get; set; }
    
        public virtual ICollection<C_PERSONA> C_PERSONA { get; set; }
    }
}
