//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PERSONA_HUELLAS
    {
        public int ID_PERSONA { get; set; }
        public byte[] HUELLA_DER1_PK { get; set; }
        public byte[] HUELLA_DER2_PK { get; set; }
        public byte[] HUELLA_DER3_PK { get; set; }
        public byte[] HUELLA_DER4_PK { get; set; }
        public byte[] HUELLA_DER5_PK { get; set; }
        public byte[] HUELLA_IZQ1_PK { get; set; }
        public byte[] HUELLA_IZQ2_PK { get; set; }
        public byte[] HUELLA_IZQ3_PK { get; set; }
        public byte[] HUELLA_IZQ4_PK { get; set; }
        public byte[] HUELLA_IZQ5_PK { get; set; }
        public byte[] HUELLA_DER1_WSQ { get; set; }
        public byte[] HUELLA_DER2_WSQ { get; set; }
        public byte[] HUELLA_DER3_WSQ { get; set; }
        public byte[] HUELLA_DER4_WSQ { get; set; }
        public byte[] HUELLA_DER5_WSQ { get; set; }
        public byte[] HUELLA_IZQ1_WSQ { get; set; }
        public byte[] HUELLA_IZQ2_WSQ { get; set; }
        public byte[] HUELLA_IZQ3_WSQ { get; set; }
        public byte[] HUELLA_IZQ4_WSQ { get; set; }
        public byte[] HUELLA_IZQ5_WSQ { get; set; }
        public byte[] HUELLA_SLAP1_WSQ { get; set; }
        public byte[] HUELLA_SLAP2_WSQ { get; set; }
        public byte[] HUELLA_SLAP3_WSQ { get; set; }
        public Nullable<bool> HUELLA_DER1_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_DER2_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_DER3_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_DER4_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_DER5_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_IZQ1_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_IZQ2_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_IZQ3_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_IZQ4_ESTATUS { get; set; }
        public Nullable<bool> HUELLA_IZQ5_ESTATUS { get; set; }
        public Nullable<bool> ora_modif_wsq_u1 { get; set; }
        public Nullable<bool> ora_modif_wsq_u2 { get; set; }
        public Nullable<bool> ora_modif_wsq_u3 { get; set; }
        public Nullable<bool> ora_modif_wsq_i1 { get; set; }
        public Nullable<bool> ora_modif_pk_u1 { get; set; }
        public Nullable<bool> ora_modif_pk_u2 { get; set; }
        public Nullable<bool> ora_modif_pk_u3 { get; set; }
        public Nullable<bool> ora_modif_pk_i1 { get; set; }
        public Nullable<bool> ora_modif_status_der { get; set; }
        public Nullable<bool> ora_modif_status_izq { get; set; }
        public int CONTROL_HUELLAS { get; set; }
        public Nullable<int> ZZ_MIGRA_IP104040 { get; set; }
        public string FG { get; set; }
    }
}
