//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PERSONA_DOC
    {
        public int ID_PERSONA { get; set; }
        public int ID_TIPO_DOCUMENTO { get; set; }
        public byte[] DOC_IMAGEN { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public Nullable<bool> ora_modif_docper_i { get; set; }
        public Nullable<int> ora_modif_clvdcmprs_ref { get; set; }
        public Nullable<int> ZZ_MIGRA_IP104040 { get; set; }
    
        public virtual C_PERSONA C_PERSONA { get; set; }
    }
}
