//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PERSONA
    {
        public C_PERSONA()
        {
            this.C_PERSONA_IMG = new HashSet<C_PERSONA_IMG>();
            this.C_PERSONA_DOC = new HashSet<C_PERSONA_DOC>();
        }
    
        public int ID_PERSONA { get; set; }
        public string PER_NOMBRE { get; set; }
        public string PER_APELLIDO_PATERNO { get; set; }
        public string PER_APELLIDO_MATERNO { get; set; }
        public Nullable<System.DateTime> PER_FCH_NACIMIENTO { get; set; }
        public string PER_RFC { get; set; }
        public string PER_CURP { get; set; }
        public string PER_DOM_CALLE { get; set; }
        public string PER_DOM_NUM_EXT { get; set; }
        public string PER_DOM_NUM_INT { get; set; }
        public string PER_DOM_REF_ADIC { get; set; }
        public string PER_DOM_CP { get; set; }
        public Nullable<int> ID_COLONIA { get; set; }
        public Nullable<int> ID_DELEG_MUNICIPIO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_SEXO { get; set; }
        public Nullable<int> ID_ESTADO_CIVIL { get; set; }
        public string PER_IFE { get; set; }
        public Nullable<int> ID_NACIONALIDAD { get; set; }
        public Nullable<int> ID_TIPO_SANGRE { get; set; }
        public Nullable<int> ID_INSTITUCION { get; set; }
        public string PER_TELEFONO { get; set; }
        public string PER_NOTAS { get; set; }
        public Nullable<int> ID_ENTIDAD_NACIMIENTO { get; set; }
        public string PER_DOM_CP_SEPOMEX { get; set; }
        public Nullable<bool> PER_CURP_CORRECTO { get; set; }
        public Nullable<bool> PER_RFC_CORRECTO { get; set; }
        public Nullable<bool> PER_IFE_CORRECTO { get; set; }
        public string PER_CORREO { get; set; }
        public Nullable<int> ID_TIPO_TELEFONO { get; set; }
        public string PER_TELEFONO_LADA { get; set; }
        public Nullable<System.DateTime> FCH_CREACION { get; set; }
        public Nullable<bool> DATOS_VALIDADOS { get; set; }
        public string ID_D_CURSO { get; set; }
        public Nullable<int> ID_PROFESION { get; set; }
        public Nullable<int> ID_PAIS_NACIMIENTO { get; set; }
        public Nullable<bool> DONA_ORGANOS { get; set; }
        public Nullable<int> ID_RESTRICCIONES_FISICAS { get; set; }
        public Nullable<int> ID_BOCA { get; set; }
        public Nullable<int> ID_CABELLO { get; set; }
        public Nullable<int> ID_CARA { get; set; }
        public Nullable<int> ID_COMPLEXION { get; set; }
        public Nullable<int> ID_NARIZ { get; set; }
        public Nullable<int> ID_OJOS { get; set; }
        public Nullable<int> ID_PIEL { get; set; }
        public Nullable<decimal> PER_ESTATURA { get; set; }
        public string PER_SENAS_PART { get; set; }
        public string TUT_APELLIDO_PATERNO { get; set; }
        public string TUT_APELLIDO_MATERNO { get; set; }
        public string TUT_NOMBRE { get; set; }
        public Nullable<int> ora_modif_MvCrdl_prsIgu1 { get; set; }
        public Nullable<bool> ora_modif_MvCrdl_i1 { get; set; }
        public Nullable<int> ora_modif_MvCrdl_prsMig1 { get; set; }
        public Nullable<System.DateTime> ora_modif_MvCrdl_FchAct { get; set; }
        public Nullable<System.DateTime> ora_modif_MvCrdl_FchHis { get; set; }
        public Nullable<bool> ora_modif_MvCrdl_SeSusti { get; set; }
        public Nullable<int> ZZ_MIGRA_IP104040 { get; set; }
        public Nullable<decimal> PER_PESO { get; set; }
    
        public virtual ICollection<C_PERSONA_IMG> C_PERSONA_IMG { get; set; }
        public virtual ICollection<C_PERSONA_DOC> C_PERSONA_DOC { get; set; }
        public virtual C_COLONIA C_COLONIA { get; set; }
        public virtual C_ESTADO_CIVIL C_ESTADO_CIVIL { get; set; }
        public virtual C_PROFESION C_PROFESION { get; set; }
        public virtual C_RESTRICCIONES_FISICAS C_RESTRICCIONES_FISICAS { get; set; }
    }
}
