//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SILCVEREntities : DbContext
    {
        public SILCVEREntities()
            : base("name=SILCVEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_PERSONA> C_PERSONA { get; set; }
        public DbSet<C_PERSONA_DOC> C_PERSONA_DOC { get; set; }
        public DbSet<C_PERSONA_HUELLAS> C_PERSONA_HUELLAS { get; set; }
        public DbSet<C_PERSONA_IMG> C_PERSONA_IMG { get; set; }
        public DbSet<C_COLONIA> C_COLONIA { get; set; }
        public DbSet<C_DELEG_MUNICIPIO> C_DELEG_MUNICIPIO { get; set; }
        public DbSet<C_ESTADO_CIVIL> C_ESTADO_CIVIL { get; set; }
        public DbSet<C_PROFESION> C_PROFESION { get; set; }
        public DbSet<C_RESTRICCIONES_FISICAS> C_RESTRICCIONES_FISICAS { get; set; }
        public DbSet<vLicencias_NEW> vLicencias_NEW { get; set; }
        public DbSet<vLicencias_Imagen_New> vLicencias_Imagen_New { get; set; }
        public DbSet<vLicencias_UNION> vLicencias_UNION { get; set; }
    }
}
