//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLicencias_Imagen_New
    {
        public decimal ID_ALTERNA { get; set; }
        public decimal ID_TIPO_IMAGEN { get; set; }
        public Nullable<decimal> ENTIDAD_ID { get; set; }
        public Nullable<decimal> DELEGACION { get; set; }
        public string NO_LICENCI { get; set; }
        public Nullable<System.DateTime> Expedicion { get; set; }
        public Nullable<System.DateTime> VENCIMIENT { get; set; }
        public string OFIEXP { get; set; }
        public Nullable<decimal> IMAGENKEY { get; set; }
        public byte[] IMAGEN { get; set; }
    }
}
