//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLicencias_NEW
    {
        public int ID_ALTERNA { get; set; }
        public byte SEXO { get; set; }
        public string EXPEDICION { get; set; }
        public string VENCIMIENT { get; set; }
        public string TIPO_DE_LIC { get; set; }
        public string NO_LICENCI { get; set; }
        public short PERIODO { get; set; }
        public string OFIEXP { get; set; }
        public int ENTIDAD_ID { get; set; }
        public Nullable<short> DELEGACION { get; set; }
        public int SANGRE { get; set; }
        public string RESTRICCION { get; set; }
        public string NOMBRECOND { get; set; }
        public string APELLIDOPA { get; set; }
        public string APELLIDOMA { get; set; }
        public Nullable<System.DateTime> FECHANACIM { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public Nullable<short> NACIONALIDAD { get; set; }
        public Nullable<short> ENTIDAD_CONDUCTOR { get; set; }
        public Nullable<short> MUN_ID { get; set; }
        public string MUNICIPIO { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string CODPOSTAL { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<System.DateTime> EnrollmentTime { get; set; }
    }
}
