//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaLicencias
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLicencias_UNION
    {
        public int ID_ALTERNA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public Nullable<System.DateTime> FCH_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public int ESTATUS_REGISTRO { get; set; }
        public string Busqueda { get; set; }
    }
}
